[package]
name = "eider-api"
version.workspace = true
edition.workspace = true

[dependencies]
infer = { path = "../infer" }

async-stream.workspace = true
axum.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
